package com.voyageone.retail.biz.process.dao;

import com.voyageone.retail.biz.process.model.RbLog;
import org.springframework.stereotype.Repository;

@Repository
public interface RbLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rb_log
     *
     * @mbg.generated Sat May 29 15:39:39 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rb_log
     *
     * @mbg.generated Sat May 29 15:39:39 CST 2021
     */
    int insert(RbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rb_log
     *
     * @mbg.generated Sat May 29 15:39:39 CST 2021
     */
    int insertSelective(RbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rb_log
     *
     * @mbg.generated Sat May 29 15:39:39 CST 2021
     */
    RbLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rb_log
     *
     * @mbg.generated Sat May 29 15:39:39 CST 2021
     */
    int updateByPrimaryKeySelective(RbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rb_log
     *
     * @mbg.generated Sat May 29 15:39:39 CST 2021
     */
    int updateByPrimaryKey(RbLog record);
}