package com.voyageone.retail.oauth.dao;

import com.voyageone.retail.oauth.model.RetailUser;
import org.springframework.stereotype.Repository;

@Repository
public interface RetailUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int insert(RetailUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int insertSelective(RetailUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    RetailUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int updateByPrimaryKeySelective(RetailUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int updateByPrimaryKey(RetailUser record);
}