package com.voyageone.retail.oauth.dao;

import com.voyageone.retail.oauth.model.RetailRoleGroupMapping;
import org.springframework.stereotype.Repository;

@Repository
public interface RetailRoleGroupMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_group_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_group_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insert(RetailRoleGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_group_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insertSelective(RetailRoleGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_group_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    RetailRoleGroupMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_group_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKeySelective(RetailRoleGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_group_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKey(RetailRoleGroupMapping record);
}