package com.voyageone.retail.oauth.dao;

import com.voyageone.retail.oauth.model.RetailAuth;
import org.springframework.stereotype.Repository;

@Repository
public interface RetailAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_auth
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_auth
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insert(RetailAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_auth
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insertSelective(RetailAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_auth
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    RetailAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_auth
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKeySelective(RetailAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_auth
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKey(RetailAuth record);
}