package com.voyageone.retail.oauth.dao;

import com.voyageone.retail.oauth.model.RetailUserRoleMapping;
import org.springframework.stereotype.Repository;

@Repository
public interface RetailUserRoleMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user_role_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user_role_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insert(RetailUserRoleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user_role_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insertSelective(RetailUserRoleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user_role_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    RetailUserRoleMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user_role_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKeySelective(RetailUserRoleMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_user_role_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKey(RetailUserRoleMapping record);
}