package com.voyageone.retail.oauth.dao;

import com.voyageone.retail.oauth.model.RetailMenu;
import org.springframework.stereotype.Repository;

@Repository
public interface RetailMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_menu
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_menu
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insert(RetailMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_menu
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insertSelective(RetailMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_menu
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    RetailMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_menu
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKeySelective(RetailMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_menu
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKey(RetailMenu record);
}