package com.voyageone.retail.oauth.dao;

import com.voyageone.retail.oauth.model.RetailRole;
import org.springframework.stereotype.Repository;

@Repository
public interface RetailRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int insert(RetailRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int insertSelective(RetailRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    RetailRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int updateByPrimaryKeySelective(RetailRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    int updateByPrimaryKey(RetailRole record);
}