package com.voyageone.retail.oauth.dao;

import com.voyageone.retail.oauth.model.RetailRoleModuleMenuMapping;
import org.springframework.stereotype.Repository;

@Repository
public interface RetailRoleModuleMenuMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_module_menu_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_module_menu_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insert(RetailRoleModuleMenuMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_module_menu_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insertSelective(RetailRoleModuleMenuMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_module_menu_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    RetailRoleModuleMenuMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_module_menu_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKeySelective(RetailRoleModuleMenuMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_role_module_menu_mapping
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKey(RetailRoleModuleMenuMapping record);
}