package com.voyageone.retail.oauth.dao;

import com.voyageone.retail.oauth.model.RetailModule;
import org.springframework.stereotype.Repository;

@Repository
public interface RetailModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_module
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_module
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insert(RetailModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_module
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int insertSelective(RetailModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_module
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    RetailModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_module
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKeySelective(RetailModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table retail_module
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    int updateByPrimaryKey(RetailModule record);
}