package com.voyageone.retail.biz.process.model;

import java.util.Date;

public abstract class RbLog_Field extends BaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_log.id
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_log.op
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    private String op;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rb_log.create_time
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_log.id
     *
     * @return the value of rb_log.id
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_log.id
     *
     * @param id the value for rb_log.id
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_log.op
     *
     * @return the value of rb_log.op
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    public String getOp() {
        return op;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_log.op
     *
     * @param op the value for rb_log.op
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    public void setOp(String op) {
        this.op = op == null ? null : op.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rb_log.create_time
     *
     * @return the value of rb_log.create_time
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rb_log.create_time
     *
     * @param createTime the value for rb_log.create_time
     *
     * @mbg.generated Sat May 29 15:42:45 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}