#mysql
spring:
  datasource:
    url: jdbc:mysql://10.0.0.132:3306/flowable?characterEncoding=UTF-8&serverTimezone=UTC&useUnicode=true&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: Hua_!23shang
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 400
    maximum-pool-size: 400
    maximum-lifetime: 18000000
    maximum-idle: 30
    maximum-wait: 10000
    min-idle: 10
    initial-size: 50
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=60000)
