package com.voyageone.retail.oauth.model;

import com.voyageone.retail.oauth.model.bean.RetailBaseModel;
import java.util.Date;

public abstract class RetailUser_Field extends RetailBaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user.id
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user.name
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user.phone_number
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user.age
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user.gender
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user.birthday
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    private Date birthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user.id
     *
     * @return the value of retail_user.id
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user.id
     *
     * @param id the value for retail_user.id
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user.name
     *
     * @return the value of retail_user.name
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user.name
     *
     * @param name the value for retail_user.name
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user.phone_number
     *
     * @return the value of retail_user.phone_number
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user.phone_number
     *
     * @param phoneNumber the value for retail_user.phone_number
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user.age
     *
     * @return the value of retail_user.age
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user.age
     *
     * @param age the value for retail_user.age
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user.gender
     *
     * @return the value of retail_user.gender
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user.gender
     *
     * @param gender the value for retail_user.gender
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user.birthday
     *
     * @return the value of retail_user.birthday
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user.birthday
     *
     * @param birthday the value for retail_user.birthday
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
}