package com.voyageone.retail.oauth.model;

import com.voyageone.retail.oauth.model.bean.RetailBaseModel;

public abstract class RetailGroup_Field extends RetailBaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_group.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_group.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_group.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_group.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_group.id
     *
     * @return the value of retail_group.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_group.id
     *
     * @param id the value for retail_group.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_group.name
     *
     * @return the value of retail_group.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_group.name
     *
     * @param name the value for retail_group.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_group.type
     *
     * @return the value of retail_group.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_group.type
     *
     * @param type the value for retail_group.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_group.parent_id
     *
     * @return the value of retail_group.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_group.parent_id
     *
     * @param parentId the value for retail_group.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}