package com.voyageone.retail.oauth.model;

import com.voyageone.retail.oauth.model.bean.RetailBaseModel;

public abstract class RetailModule_Field extends RetailBaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_module.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_module.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_module.icon_url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_module.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_module.url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_module.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_module.id
     *
     * @return the value of retail_module.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_module.id
     *
     * @param id the value for retail_module.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_module.name
     *
     * @return the value of retail_module.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_module.name
     *
     * @param name the value for retail_module.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_module.icon_url
     *
     * @return the value of retail_module.icon_url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_module.icon_url
     *
     * @param iconUrl the value for retail_module.icon_url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_module.type
     *
     * @return the value of retail_module.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_module.type
     *
     * @param type the value for retail_module.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_module.url
     *
     * @return the value of retail_module.url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_module.url
     *
     * @param url the value for retail_module.url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_module.parent_id
     *
     * @return the value of retail_module.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_module.parent_id
     *
     * @param parentId the value for retail_module.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}