package com.voyageone.retail.oauth.model;

import com.voyageone.retail.oauth.model.bean.RetailBaseModel;

public abstract class RetailUserRoleMapping_Field extends RetailBaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user_role_mapping.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user_role_mapping.user_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user_role_mapping.role_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_user_role_mapping.status
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user_role_mapping.id
     *
     * @return the value of retail_user_role_mapping.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user_role_mapping.id
     *
     * @param id the value for retail_user_role_mapping.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user_role_mapping.user_id
     *
     * @return the value of retail_user_role_mapping.user_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user_role_mapping.user_id
     *
     * @param userId the value for retail_user_role_mapping.user_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user_role_mapping.role_id
     *
     * @return the value of retail_user_role_mapping.role_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user_role_mapping.role_id
     *
     * @param roleId the value for retail_user_role_mapping.role_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_user_role_mapping.status
     *
     * @return the value of retail_user_role_mapping.status
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_user_role_mapping.status
     *
     * @param status the value for retail_user_role_mapping.status
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}