package com.voyageone.retail.oauth.model;

import com.voyageone.retail.oauth.model.bean.RetailBaseModel;

public abstract class RetailAuth_Field extends RetailBaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_auth.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_auth.user_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_auth.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_auth.identifier
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_auth.token
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_auth.id
     *
     * @return the value of retail_auth.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_auth.id
     *
     * @param id the value for retail_auth.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_auth.user_id
     *
     * @return the value of retail_auth.user_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_auth.user_id
     *
     * @param userId the value for retail_auth.user_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_auth.type
     *
     * @return the value of retail_auth.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_auth.type
     *
     * @param type the value for retail_auth.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_auth.identifier
     *
     * @return the value of retail_auth.identifier
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_auth.identifier
     *
     * @param identifier the value for retail_auth.identifier
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_auth.token
     *
     * @return the value of retail_auth.token
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_auth.token
     *
     * @param token the value for retail_auth.token
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}