package com.voyageone.retail.oauth.model;

import com.voyageone.retail.oauth.model.bean.RetailBaseModel;

public abstract class RetailRole_Field extends RetailBaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_role.id
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_role.name
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_role.id
     *
     * @return the value of retail_role.id
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_role.id
     *
     * @param id the value for retail_role.id
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_role.name
     *
     * @return the value of retail_role.name
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_role.name
     *
     * @param name the value for retail_role.name
     *
     * @mbg.generated Fri Jan 15 16:12:31 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}