package com.voyageone.retail.oauth.model;

import com.voyageone.retail.oauth.model.bean.RetailBaseModel;

public abstract class RetailMenu_Field extends RetailBaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_menu.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_menu.module_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_menu.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_menu.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_menu.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column retail_menu.url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_menu.id
     *
     * @return the value of retail_menu.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_menu.id
     *
     * @param id the value for retail_menu.id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_menu.module_id
     *
     * @return the value of retail_menu.module_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_menu.module_id
     *
     * @param moduleId the value for retail_menu.module_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_menu.parent_id
     *
     * @return the value of retail_menu.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_menu.parent_id
     *
     * @param parentId the value for retail_menu.parent_id
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_menu.type
     *
     * @return the value of retail_menu.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_menu.type
     *
     * @param type the value for retail_menu.type
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_menu.name
     *
     * @return the value of retail_menu.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_menu.name
     *
     * @param name the value for retail_menu.name
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column retail_menu.url
     *
     * @return the value of retail_menu.url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column retail_menu.url
     *
     * @param url the value for retail_menu.url
     *
     * @mbg.generated Fri Jan 15 16:28:24 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}